[server]
port = 8502
address = "localhost"
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[theme]
base="light"
backgroundColor="#00EFF0"
secondaryBackgroundColor="#fafafcff"
textColor="#262730"
font="sans serif"